Reformat test

diff --git a/auto-install b/auto-install
--- a/auto-install
+++ b/auto-install
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 WOS=''
-LOCAL=`dirname "$(readlink -f "$0")"`
+LOCAL=$(dirname "$(readlink -f "$0")")
 
-function is_working {
-    if [ $? -eq 0 ];then
+function is_working() {
+    if [ $? -eq 0 ]; then
         success "$1"
     else
         error "$1"
     fi
 }
 
-function detectOS {
+function detectOS() {
     if [ -f /etc/lsb-release ]; then
         WOS=$(cat /etc/lsb-release | grep DISTRIB_ID | sed 's/^.*=//' | sed -e 's/\(.*\)/\L\1/')
     elif [ -f /etc/os-release ]; then
@@ -28,12 +28,12 @@ function detectOS {
     fi
 }
 
-function home_ln {
-    ln -sfn `pwd`/$1 $2 &>>$logFile
+function home_ln() {
+    ln -sfn $(pwd)/$1 $2 &>>$logFile
     is_working "ln $1 on $2"
 }
 
-function home_folder {
+function home_folder() {
     info "Symbolic links to home..."
     for f in $LOCAL/$1/*; do
         DEST=$(basename $f)
@@ -42,7 +42,7 @@ function home_folder {
     done
 }
 
-function conf_folder {
+function conf_folder() {
     info "Symbolic links to .config"
     mkdir -p ~/.config
     for f in $LOCAL/$1/*; do
@@ -53,28 +53,28 @@ function conf_folder {
 
 }
 
-function home_cp {
-    unalias cp > /dev/null 2>&1
-    cp -fr `pwd`/$1 ~/$1 > /dev/null 2>&1
+function home_cp() {
+    unalias cp >/dev/null 2>&1
+    cp -fr $(pwd)/$1 ~/$1 >/dev/null 2>&1
     is_working "Copy $1 to ~"
-    alias cp="cp -iv" > /dev/null 2>&1
+    alias cp="cp -iv" >/dev/null 2>&1
 }
 
 # run detectOS before
-function ins {
+function ins() {
     all="$@" #for is_working function
     info "Installation: $all "
-    if [ "$WOS" = "ubuntu" ] || [ "$WOS" = "debian" ] || [ "$WOS" = "raspbian" ] ;then
+    if [ "$WOS" = "ubuntu" ] || [ "$WOS" = "debian" ] || [ "$WOS" = "raspbian" ]; then
         sudo apt update -y &>>$logFile
         sudo apt install $@ -y &>>$logFile
         is_working "$all installed"
-    elif [ "$WOS" = "fedora" ] ;then
+    elif [ "$WOS" = "fedora" ]; then
         sudo dnf install -y --nogpgcheck https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
         sudo dnf install -y --nogpgcheck https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
         sudo dnf update -y &>>$logFile
         sudo dnf install $@ -y &>>$logFile
         is_working "$all installed"
-    elif [ "$WOS" = "arch" ] ;then
+    elif [ "$WOS" = "arch" ]; then
         sudo pacman -S $@ --needed --noconfirm &>>$logFile
         is_working "$all installed"
     else
@@ -82,13 +82,13 @@ function ins {
     fi
 }
 
-function aur_ins {
+function aur_ins() {
     all="$@" #for is_working function
     info "Installation: $all "
-    if [ "$WOS" = "arch" ] ;then
+    if [ "$WOS" = "arch" ]; then
         # Aur tool install
         pikaur -v &>/dev/null
-        if [ $? -ne 0 ];then
+        if [ $? -ne 0 ]; then
             arch_package_install https://aur.archlinux.org/pikaur.git
         fi
         pikaur -S $@ --noedit --needed --noconfirm &>>$logFile
@@ -99,22 +99,22 @@ function aur_ins {
 
 }
 
-function arch_package_install {
+function arch_package_install() {
     info "Arch install: $1"
     sudo pacman -S --needed base-devel git --noconfirm &>>$logFile
-    tmpD=`mktemp -d`
+    tmpD=$(mktemp -d)
     git clone $1 $tmpD &>>$logFile
     cd $tmpD
-    makepkg -fsri --skipinteg --noconfirm  &>>$logFile
+    makepkg -fsri --skipinteg --noconfirm &>>$logFile
     cd $LOCAL
 }
 
-function git_clone {
+function git_clone() {
     info "Cloning $1"
-    if $force ; then
+    if $force; then
         rm -rf $2
     fi
-    if [ ! -e "$2" ] ; then
+    if [ ! -e "$2" ]; then
         git clone --depth=1 $1 $2 &>>$logFile
         is_working "Cloned: $1 to $2"
     else
@@ -122,7 +122,7 @@ function git_clone {
     fi
 }
 
-function basic_install {
+function basic_install() {
     info "Basic installation"
     # Basic packages
     ins vim git htop iftop iotop tree zsh make wget sudo rsync
@@ -140,33 +140,32 @@ function basic_install {
     cd $LOCAL
 }
 
-function dev_env_install {
-    if [ "$WOS" = "arch" ];then
+function dev_env_install() {
+    if [ "$WOS" = "arch" ]; then
         {
             file="$LOCAL/arch-package-list"
-            if [ -f "$file" ];then
+            if [ -f "$file" ]; then
                 info "Arch dev inv installation"
                 # .config links
                 conf_folder conf_conf
                 # TODO add manual confs powertop + i3sleep + tlp + add package check before install
                 list=""
-                while IFS= read -r line
-                do
-                    char=`echo $line| head -c1`
+                while IFS= read -r line; do
+                    char=$(echo $line | head -c1)
                     if [ "$char" != "#" ]; then
                         list="$list $line"
                     fi
-                done < "$file"
+                done <"$file"
 
                 aur_ins $list
             else
                 error "Missing $file"
             fi
         }
-else
-    {
-        error "Arch OS is needed for this installation"
-    }
+    else
+        {
+            error "Arch OS is needed for this installation"
+        }
     fi
 
 }
@@ -174,13 +173,12 @@ else
 function mainScript() {
     echo -n
     info 'Script started'
-    if [ -z "$EDITOR" ]
-    then
+    if [ -z "$EDITOR" ]; then
         export EDITOR=nano
     fi
     detectOS
     basic_install
-    if [ "$WOS" = "arch" ];then
+    if [ "$WOS" = "arch" ]; then
         seek_confirmation 'Install Dev Env ?'
         if is_confirmed; then
             dev_env_install
@@ -191,7 +189,7 @@ function mainScript() {
 function trapCleanup() {
     echo ""
     # Delete temp files, if any
-    if [ -d "${tmpDir}"  ] ; then
+    if [ -d "${tmpDir}" ]; then
         rm -r "${tmpDir}"
     fi
     die "Exit trapped. In function: '${FUNCNAME[*]}'"
@@ -200,12 +198,12 @@ function trapCleanup() {
 
 function safeExit() {
     # Delete temp files, if any
-    if [ -d "${tmpDir}"  ] ; then
+    if [ -d "${tmpDir}" ]; then
         rm -r "${tmpDir}"
     fi
     trap - INT TERM EXIT
-    if $printLog ; then
-        echo -e "$(date +"%r") ${blue}$(printf "[%7s]" "info") "Logfile: $logFile"${reset}";
+    if $printLog; then
+        echo -e "$(date +"%r") ${blue}$(printf "[%7s]" "info") "Logfile: $logFile"${reset}"
     fi
     exit
 
@@ -247,7 +245,6 @@ tmpDir="/tmp/${scriptName}.$RANDOM.$RANDOM.$RANDOM.$$"
 # Log is only used when the '-l' flag is set.
 logFile="/tmp/${scriptName}.log"
 
-
 # Options and Usage
 # -----------------------------------
 usage() {
@@ -271,10 +268,10 @@ optstring=h
 unset options
 while (($#)); do
     case $1 in
-        # If option is of type -ab
-        -[!-]?*)
+    # If option is of type -ab
+    -[!-]?*)
         # Loop over each character starting with the second
-        for ((i=1; i < ${#1}; i++)); do
+        for ((i = 1; i < ${#1}; i++)); do
             c=${1:i:1}
 
             # Add current char to options
@@ -282,19 +279,19 @@ while (($#)); do
 
             # If option takes a required argument, and it's not the last char make
             # the rest of the string its argument
-            if [[ $optstring = *"$c:"* && ${1:i+1}  ]]; then
+            if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
                 options+=("${1:i+1}")
                 break
             fi
         done
         ;;
 
-        # If option is of type --foo=bar
-        --?*=*) options+=("${1%%=*}" "${1#*=}") ;;
-        # add --endopts for --
-        --) options+=(--endopts) ;;
-        # Otherwise, nothing special
-        *) options+=("$1") ;;
+    # If option is of type --foo=bar
+    --?*=*) options+=("${1%%=*}" "${1#*=}") ;;
+    # add --endopts for --
+    --) options+=(--endopts) ;;
+    # Otherwise, nothing special
+    *) options+=("$1") ;;
     esac
     shift
 done
@@ -309,15 +306,21 @@ unset options
 # Read the options and set stuff
 while [[ $1 = -?* ]]; do
     case $1 in
-        -h|--help) usage >&2; safeExit ;;
-        -v|--verbose) verbose=true ;;
-        -l|--log) printLog=true;;
-        -q|--quiet) quiet=true ;;
-        -d|--debug) debug=true;;
-        -f|--force) force=true ;;
-        -y|--noconfirm) noconfirm=true;;
-        --endopts) shift; break ;;
-        *) die "invalid option: '$1'." ;;
+    -h | --help)
+        usage >&2
+        safeExit
+        ;;
+    -v | --verbose) verbose=true ;;
+    -l | --log) printLog=true ;;
+    -q | --quiet) quiet=true ;;
+    -d | --debug) debug=true ;;
+    -f | --force) force=true ;;
+    -y | --noconfirm) noconfirm=true ;;
+    --endopts)
+        shift
+        break
+        ;;
+    *) die "invalid option: '$1'." ;;
     esac
     shift
 done
@@ -325,47 +328,77 @@ done
 # Store the remaining part as arguments.
 args+=("$@")
 
-
 # Logging & Feedback
 # -----------------------------------------------------
 function _alert() {
-    if [ "${1}" = "error"  ]; then local color="${bold}${red}"; fi
-    if [ "${1}" = "warning"  ]; then local color="${yellow}"; fi
-    if [ "${1}" = "success"  ]; then local color="${green}"; fi
-    if [ "${1}" = "debug"  ]; then local color="${purple}"; fi
-    if [ "${1}" = "header"  ]; then local color="${bold}${tan}"; fi
-    if [ "${1}" = "input"  ]; then local color="${bold}"; fi
-    if [ "${1}" = "notice"  ]; then local color="${blue}"; fi
-    if [ "${1}" = "info"  ] || [ "${1}" = "notice"  ]; then local color="${blue}"; fi
+    if [ "${1}" = "error" ]; then local color="${bold}${red}"; fi
+    if [ "${1}" = "warning" ]; then local color="${yellow}"; fi
+    if [ "${1}" = "success" ]; then local color="${green}"; fi
+    if [ "${1}" = "debug" ]; then local color="${purple}"; fi
+    if [ "${1}" = "header" ]; then local color="${bold}${tan}"; fi
+    if [ "${1}" = "input" ]; then local color="${bold}"; fi
+    if [ "${1}" = "notice" ]; then local color="${blue}"; fi
+    if [ "${1}" = "info" ] || [ "${1}" = "notice" ]; then local color="${blue}"; fi
     # Don't use colors on pipes or non-recognized terminals
-    if [[ "${TERM}" != "xterm"*  ]] || [ -t 1  ]; then color=""; reset=""; fi
+    if [[ "${TERM}" != "xterm"* ]] || [ -t 1 ]; then
+        color=""
+        reset=""
+    fi
 
     # Print to console when script is not 'quiet'
-    if ${quiet} || [ "${1}" = "debug"  ]; then true; else
-        echo -e "$(date +"%T") ${color}$(printf "[%7s]" "${1}") ${_message}${reset}";
+    if ${quiet} || [ "${1}" = "debug" ]; then true; else
+        echo -e "$(date +"%T") ${color}$(printf "[%7s]" "${1}") ${_message}${reset}"
     fi
 
     # Print to Logfile
-    if ${printLog} && [ "${1}" != "input"  ] && [ "${1}" != "notice" ];  then
-        color=""; reset="" # Don't use colors in logs
-        echo -e "$(date +"%F %T") $(printf "[%7s]" "${1}") ${_message}" >> "${logFile}";
+    if ${printLog} && [ "${1}" != "input" ] && [ "${1}" != "notice" ]; then
+        color=""
+        reset="" # Don't use colors in logs
+        echo -e "$(date +"%F %T") $(printf "[%7s]" "${1}") ${_message}" >>"${logFile}"
         if [ "${1}" = "debug" ]; then
-            echo -e "$(date +"%F %T") $(printf "[%7s]" "run") `${_message} 2>&1`" >> "${logFile}" ;
+            echo -e "$(date +"%F %T") $(printf "[%7s]" "run") $(${_message} 2>&1)" >>"${logFile}"
         fi
     fi
 }
 
-function die ()       { local _message="${*} Exiting."; echo -e "$(_alert error)"; safeExit; }
-function error ()     { local _message="${*}"; echo -e "$(_alert error)";  }
-function warning ()   { local _message="${*}"; echo -e "$(_alert warning)";  }
-function notice ()    { local _message="${*}"; echo -e "$(_alert notice)";  }
-function info ()      { local _message="${*}"; echo -e "$(_alert info)";  }
-function debug ()     { local _message="${*}"; echo -n "$(_alert debug)";  }
-function success ()   { local _message="${*}"; echo -e "$(_alert success)";  }
-function input()      { local _message="${*}"; echo -n "$(_alert input)";  }
-function header()     { local _message="== ${*} ==  "; echo -e "$(_alert header)";  }
-function verbose()    { if ${verbose}; then debug "$@"; fi  }
-
+function die() {
+    local _message="${*} Exiting."
+    echo -e "$(_alert error)"
+    safeExit
+}
+function error() {
+    local _message="${*}"
+    echo -e "$(_alert error)"
+}
+function warning() {
+    local _message="${*}"
+    echo -e "$(_alert warning)"
+}
+function notice() {
+    local _message="${*}"
+    echo -e "$(_alert notice)"
+}
+function info() {
+    local _message="${*}"
+    echo -e "$(_alert info)"
+}
+function debug() {
+    local _message="${*}"
+    echo -n "$(_alert debug)"
+}
+function success() {
+    local _message="${*}"
+    echo -e "$(_alert success)"
+}
+function input() {
+    local _message="${*}"
+    echo -n "$(_alert input)"
+}
+function header() {
+    local _message="== ${*} ==  "
+    echo -e "$(_alert header)"
+}
+function verbose() { if ${verbose}; then debug "$@"; fi; }
 
 # SEEKING CONFIRMATION
 # ------------------------------------------------------
@@ -381,14 +414,14 @@ function seek_confirmation() {
 
 }
 function is_confirmed() {
-    if [[ "${REPLY}" =~ ^[Yy]$  ]] || "${noconfirm}"; then
+    if [[ "${REPLY}" =~ ^[Yy]$ ]] || "${noconfirm}"; then
         return 0
     fi
     return 1
 
 }
 function is_not_confirmed() {
-    if [[ "${REPLY}" =~ ^[Nn]$  ]]; then
+    if [[ "${REPLY}" =~ ^[Nn]$ ]]; then
         return 0
     fi
     return 1
@@ -399,10 +432,10 @@ function is_not_confirmed() {
 IFS=$' \n\t'
 
 # Run in debug mode, if set
-if ${debug}; then set -x ; fi
+if ${debug}; then set -x; fi
 
 # Exit on empty variable
-if ${strict}; then set -o nounset ; fi
+if ${strict}; then set -o nounset; fi
 
 # Bash will remember & return the highest exitcode in a chain of pipes.
 # This way you can catch the error in case mysqldump fails in `mysqldump |gzip`, for example.
@@ -413,4 +446,3 @@ mainScript
 
 # Exit cleanly
 safeExit
-
