this is my quickfix branch and i will use to do my quickfixes

diff --git a/docker_conf/tools/serv_manager/docker_manager b/docker_conf/tools/serv_manager/docker_manager
--- a/docker_conf/tools/serv_manager/docker_manager
+++ b/docker_conf/tools/serv_manager/docker_manager
@@ -105,8 +105,8 @@ reload() {
 
 boot_check() {
     [ `id -u` -ne 0 ] && echo "Must be run as root." && exit 1
-    if ! msmtp --version ; then
-        echo "msmtp must be installed."
+    if ! msmtp --version &>/dev/null ; then
+        echo "msmtp not found, exiting."
         exit 1
     fi
     [ "$#" -ne 2 ] && echo "$USAGE" && exit 1
